// Disease reference data curated from the PlantVillage dataset and
// standard horticultural literature.  Each entry maps to one of the
// 10 plants in plantData.js.  Images are sourced from PlantVillage
// (Kaggle) — see https://www.kaggle.com/datasets/emmarex/plantdisease
//
// Structure per disease:
//   name        – common disease / condition name
//   category    – Fungal | Bacterial | Viral | Pest | Nutrient | Environmental
//   severity    – Low | Medium | High
//   thumbnail   – PlantVillage Kaggle image path fragment (for future use)
//   symptoms    – what the gardener will see
//   cause       – pathogen / environmental trigger
//   treatment   – beginner-friendly action steps
//   prevention  – how to avoid it

export const DISEASE_LIBRARY = {
  tomato: [
    {
      name: 'Early Blight',
      category: 'Fungal',
      severity: 'Medium',
      thumbnail: 'Tomato___Early_blight',
      symptoms: 'Dark brown concentric rings ("target spots") on lower leaves first, spreading upward. Leaves yellow and drop.',
      cause: 'Fungus Alternaria solani — favored by warm (75–85 °F), humid weather and overhead watering.',
      treatment: 'Remove affected leaves immediately. Apply neem oil or copper-based fungicide every 7–10 days. Mulch around the base to prevent soil splash.',
      prevention: 'Rotate crops yearly. Water at the base, not overhead. Ensure good air circulation between plants.',
    },
    {
      name: 'Late Blight',
      category: 'Fungal',
      severity: 'High',
      thumbnail: 'Tomato___Late_blight',
      symptoms: 'Large, water-soaked, dark brown/greenish-black patches on leaves and stems. White fuzzy mold on leaf undersides in humid conditions. Fruit develops brown, firm rot.',
      cause: 'Oomycete Phytophthora infestans — spreads rapidly in cool (60–70 °F), wet weather.',
      treatment: 'Remove and destroy (do NOT compost) all infected parts. Apply copper fungicide. In severe cases, remove the entire plant to protect neighbors.',
      prevention: 'Avoid overhead watering. Space plants for airflow. Choose resistant varieties (labeled "LB" or "Ph").',
    },
    {
      name: 'Septoria Leaf Spot',
      category: 'Fungal',
      severity: 'Medium',
      thumbnail: 'Tomato___Septoria_leaf_spot',
      symptoms: 'Many small, circular spots (1/16–1/8 in) with dark brown margins and tan/grey centers, usually starting on lower leaves.',
      cause: 'Fungus Septoria lycopersici — spreads via rain splash and contaminated tools.',
      treatment: 'Prune affected lower leaves. Apply copper fungicide or neem oil. Sanitize pruning shears between cuts.',
      prevention: 'Mulch to prevent soil splash. Stake plants to keep foliage off the ground. Rotate crops on a 3-year cycle.',
    },
    {
      name: 'Leaf Mold',
      category: 'Fungal',
      severity: 'Low',
      thumbnail: 'Tomato___Leaf_Mold',
      symptoms: 'Pale green to yellowish spots on upper leaf surfaces. Olive-green to brown velvety mold on undersides.',
      cause: 'Fungus Passalora fulva — thrives in high humidity (>85%) and poor airflow, especially in greenhouses.',
      treatment: 'Improve ventilation. Remove badly affected leaves. Apply sulfur-based fungicide if needed.',
      prevention: 'Space plants generously. Avoid wetting foliage. Grow resistant varieties when possible.',
    },
    {
      name: 'Bacterial Spot',
      category: 'Bacterial',
      severity: 'Medium',
      thumbnail: 'Tomato___Bacterial_spot',
      symptoms: 'Small, dark, water-soaked spots on leaves that turn brown with yellow halos. Fruit develops raised, scab-like lesions.',
      cause: 'Xanthomonas bacteria — enters through wounds, spreads in warm rain.',
      treatment: 'Remove infected leaves. Apply copper-based bactericide. Avoid working with plants when wet.',
      prevention: 'Use disease-free seed/transplants. Rotate crops. Sanitize tools.',
    },
    {
      name: 'Tomato Mosaic Virus',
      category: 'Viral',
      severity: 'High',
      thumbnail: 'Tomato___Tomato_mosaic_virus',
      symptoms: 'Mottled light and dark green patches on leaves. Leaves may curl, become distorted, or develop a fern-like appearance. Stunted growth.',
      cause: 'Tobamovirus — extremely contagious, spread by touch, tools, and contaminated seed.',
      treatment: 'No cure. Remove and destroy infected plants. Wash hands and tools with soap or 10% bleach solution.',
      prevention: 'Plant resistant varieties (labeled "TMV"). Wash hands before handling plants. Avoid tobacco products near plants.',
    },
    {
      name: 'Yellow Leaf Curl Virus',
      category: 'Viral',
      severity: 'High',
      thumbnail: 'Tomato___Tomato_Yellow_Leaf_Curl_Virus',
      symptoms: 'Young leaves curl upward and turn pale yellow. Plant becomes bushy and stunted. Flowers may drop.',
      cause: 'Begomovirus — transmitted by whiteflies (Bemisia tabaci).',
      treatment: 'No cure. Remove infected plants. Control whiteflies with sticky traps, neem oil, or insecticidal soap.',
      prevention: 'Use reflective mulch to deter whiteflies. Install fine mesh row covers. Plant resistant varieties.',
    },
    {
      name: 'Spider Mites',
      category: 'Pest',
      severity: 'Medium',
      thumbnail: 'Tomato___Spider_mites_Two-spotted_spider_mite',
      symptoms: 'Tiny yellow or white speckles on leaves (stippling). Fine webbing on leaf undersides. Leaves dry out and drop.',
      cause: 'Two-spotted spider mites — thrive in hot, dry, dusty conditions.',
      treatment: 'Spray leaves with a strong water jet to dislodge mites. Apply neem oil or insecticidal soap every 5–7 days. Introduce predatory mites (Phytoseiulus) for biological control.',
      prevention: 'Keep plants well-watered. Mist foliage in dry weather. Avoid dusty conditions.',
    },
    {
      name: 'Blossom End Rot',
      category: 'Nutrient',
      severity: 'Medium',
      thumbnail: 'Tomato___healthy',
      symptoms: 'Dark, sunken, leathery patch at the bottom (blossom end) of the fruit.',
      cause: 'Calcium deficiency in the fruit — usually caused by inconsistent watering rather than lack of soil calcium.',
      treatment: 'Water deeply and consistently. Mulch to retain moisture. Avoid over-fertilizing with nitrogen.',
      prevention: 'Maintain even soil moisture. Use drip irrigation. Add crushed eggshells or gypsum at planting time.',
    },
  ],

  basil: [
    {
      name: 'Downy Mildew',
      category: 'Fungal',
      severity: 'High',
      thumbnail: 'Basil_downy_mildew',
      symptoms: 'Yellowing between leaf veins on upper surfaces. Dark, fuzzy grey-purple spore growth on undersides. Leaves drop rapidly.',
      cause: 'Oomycete Peronospora belbahrii — spreads in cool, humid conditions and via contaminated seed.',
      treatment: 'Remove affected leaves immediately. Improve airflow around plants. Apply potassium bicarbonate spray. Severely infected plants should be removed entirely.',
      prevention: 'Choose resistant varieties (e.g., "Amazel", "Devotion"). Space plants widely. Water at soil level, never overhead.',
    },
    {
      name: 'Fusarium Wilt',
      category: 'Fungal',
      severity: 'High',
      thumbnail: 'Basil_fusarium_wilt',
      symptoms: 'Stunted growth. Leaves wilt, turn yellow, then brown — often on one side first. Dark brown streaks visible inside stems when cut.',
      cause: 'Fungus Fusarium oxysporum f. sp. basilici — soil-borne, enters through roots.',
      treatment: 'No chemical cure. Remove and destroy infected plants and surrounding soil. Do not compost.',
      prevention: 'Plant resistant varieties. Use sterile potting mix. Rotate planting locations annually.',
    },
    {
      name: 'Leaf Spot',
      category: 'Bacterial',
      severity: 'Low',
      thumbnail: 'Basil_leaf_spot',
      symptoms: 'Small brown or black spots on leaves, sometimes with a yellow halo. Spots may merge in wet weather.',
      cause: 'Pseudomonas cichorii or Colletotrichum — favored by wet foliage and warm temps.',
      treatment: 'Remove spotted leaves. Apply copper spray. Ensure good air circulation.',
      prevention: 'Water at the base. Avoid overhead irrigation. Space plants for airflow.',
    },
    {
      name: 'Aphids',
      category: 'Pest',
      severity: 'Low',
      thumbnail: 'Basil_aphids',
      symptoms: 'Clusters of tiny green or black insects on new growth and leaf undersides. Sticky honeydew residue. Curling leaves.',
      cause: 'Various aphid species — attracted to tender new growth.',
      treatment: 'Blast off with a strong water spray. Apply insecticidal soap or neem oil. Introduce ladybugs.',
      prevention: 'Inspect new transplants. Companion-plant with chives or marigolds to repel aphids.',
    },
  ],

  zucchini: [
    {
      name: 'Powdery Mildew',
      category: 'Fungal',
      severity: 'Medium',
      thumbnail: 'Squash_Powdery_mildew',
      symptoms: 'White, powdery coating on upper leaf surfaces. Leaves yellow, become brittle, and die back. Reduced fruit production.',
      cause: 'Podosphaera xanthii or Erysiphe cichoracearum — spreads in warm, dry days with cool nights.',
      treatment: 'Remove heavily infected leaves. Spray with a solution of 1 tbsp baking soda + 1 tsp liquid soap per gallon of water, or apply neem oil every 7 days.',
      prevention: 'Space plants for good airflow. Water at the base. Choose resistant varieties.',
    },
    {
      name: 'Blossom End Rot',
      category: 'Nutrient',
      severity: 'Medium',
      thumbnail: 'Zucchini_blossom_end_rot',
      symptoms: 'Dark, water-soaked, sunken area at the blossom end of young fruit. Fruit may rot and fall off.',
      cause: 'Calcium deficiency triggered by uneven watering or root damage.',
      treatment: 'Water deeply and consistently — drip irrigation is ideal. Mulch to even out soil moisture.',
      prevention: 'Maintain consistent watering schedule. Add calcium (crushed eggshells or gypsum) to soil at planting.',
    },
    {
      name: 'Squash Vine Borer',
      category: 'Pest',
      severity: 'High',
      thumbnail: 'Zucchini_vine_borer',
      symptoms: 'Sudden wilting of one or more vines despite adequate water. Sawdust-like frass (excrement) at the base of stems. Hollow, mushy stems.',
      cause: 'Larvae of the clearwing moth Melittia cucurbitae — adults lay eggs at the base of stems in early summer.',
      treatment: 'Slit the stem lengthwise near the frass, remove the larva by hand, and bury the damaged stem in moist soil to encourage new roots. Apply Bt (Bacillus thuringiensis) to stem bases.',
      prevention: 'Cover stems with row cover until flowering. Wrap lower stems with aluminum foil. Succession-plant to have backups.',
    },
    {
      name: 'Squash Bug',
      category: 'Pest',
      severity: 'Medium',
      thumbnail: 'Zucchini_squash_bug',
      symptoms: 'Grey-brown shield-shaped bugs on undersides of leaves and at stem joints. Wilting, yellowing leaves. Bronze egg clusters on leaf undersides.',
      cause: 'Anasa tristis — adults overwinter in garden debris and emerge in spring.',
      treatment: 'Hand-pick adults and scrape off egg clusters. Place boards near plants at night — bugs will hide underneath and can be collected in the morning. Apply neem oil.',
      prevention: 'Clean up plant debris in fall. Use row covers early in the season. Companion-plant with nasturtiums.',
    },
  ],

  'bush-beans': [
    {
      name: 'Bean Rust',
      category: 'Fungal',
      severity: 'Medium',
      thumbnail: 'Bean_rust',
      symptoms: 'Small, reddish-brown pustules on leaf undersides. Upper leaf surface shows yellow spots. Severe cases cause leaf drop.',
      cause: 'Fungus Uromyces appendiculatus — spreads by wind and rain in warm (65–85 °F), humid weather.',
      treatment: 'Remove infected leaves. Apply sulfur-based fungicide. Avoid overhead watering.',
      prevention: 'Plant resistant varieties. Space plants for airflow. Rotate crops yearly.',
    },
    {
      name: 'Bean Mosaic Virus',
      category: 'Viral',
      severity: 'High',
      thumbnail: 'Bean_mosaic',
      symptoms: 'Light and dark green mosaic pattern on leaves. Leaves curl downward. Stunted growth. Deformed pods.',
      cause: 'Bean common mosaic virus (BCMV) — spread by aphids and contaminated seed.',
      treatment: 'No cure. Remove and destroy infected plants. Control aphids with insecticidal soap.',
      prevention: 'Plant certified virus-free seed. Choose resistant varieties. Control aphid populations.',
    },
    {
      name: 'Anthracnose',
      category: 'Fungal',
      severity: 'Medium',
      thumbnail: 'Bean_anthracnose',
      symptoms: 'Dark, sunken lesions on pods, stems, and leaves. Lesions may have pinkish spore ooze in wet weather.',
      cause: 'Fungus Colletotrichum lindemuthianum — spread by infected seed and rain splash.',
      treatment: 'Remove infected plant parts. Apply copper-based fungicide. Avoid working with wet plants.',
      prevention: 'Use disease-free seed. Rotate crops on a 2–3 year cycle. Avoid overhead watering.',
    },
    {
      name: 'Mexican Bean Beetle',
      category: 'Pest',
      severity: 'Medium',
      thumbnail: 'Bean_beetle',
      symptoms: 'Lacy, skeletonized leaves (tissue eaten from underneath, leaving veins). Yellow-orange beetle larvae with spines on leaf undersides.',
      cause: 'Epilachna varivestis — a ladybug relative that feeds on bean foliage.',
      treatment: 'Hand-pick beetles, larvae, and yellow egg clusters. Apply neem oil or spinosad. Introduce parasitic wasps (Pediobius foveolatus).',
      prevention: 'Use floating row covers until flowering. Clean up debris at season end. Plant early to outgrow damage.',
    },
  ],

  'bell-pepper': [
    {
      name: 'Bacterial Spot',
      category: 'Bacterial',
      severity: 'Medium',
      thumbnail: 'Pepper_bell___Bacterial_spot',
      symptoms: 'Small, dark, water-soaked spots on leaves and fruit. Spots enlarge and turn brown. Leaves may drop.',
      cause: 'Xanthomonas campestris pv. vesicatoria — enters through wounds, spreads in warm rain.',
      treatment: 'Remove infected leaves. Apply copper-based bactericide weekly during wet periods. Avoid overhead watering.',
      prevention: 'Use disease-free transplants. Rotate crops. Sanitize tools and stakes.',
    },
    {
      name: 'Blossom End Rot',
      category: 'Nutrient',
      severity: 'Medium',
      thumbnail: 'Pepper_blossom_end_rot',
      symptoms: 'Dark, sunken, leathery area at the bottom of the fruit. Appears when fruit is half grown.',
      cause: 'Calcium transport issue caused by inconsistent watering, not necessarily low soil calcium.',
      treatment: 'Water deeply and regularly. Mulch to retain soil moisture. Remove affected fruit so the plant redirects energy.',
      prevention: 'Use drip irrigation. Avoid over-fertilizing with nitrogen. Mulch heavily.',
    },
    {
      name: 'Aphids',
      category: 'Pest',
      severity: 'Low',
      thumbnail: 'Pepper_aphids',
      symptoms: 'Clusters of tiny green, yellow, or black insects on new growth. Sticky honeydew. Curling or distorted leaves.',
      cause: 'Green peach aphid and other species — especially active in spring.',
      treatment: 'Blast with water. Apply insecticidal soap or neem oil. Release ladybugs or lacewings.',
      prevention: 'Companion-plant with basil, chives, or marigolds. Inspect transplants before planting.',
    },
    {
      name: 'Sunscald',
      category: 'Environmental',
      severity: 'Low',
      thumbnail: 'Pepper_sunscald',
      symptoms: 'Pale, papery, sunken patches on the side of fruit facing the sun. Patch may turn white, then brown or moldy.',
      cause: 'Direct intense sunlight on exposed fruit — often after heavy pruning removes protective leaf cover.',
      treatment: 'Leave affected fruit; it is still safe to eat if the damage is minor. Provide shade cloth during heat waves.',
      prevention: 'Avoid over-pruning. Let foliage naturally shade fruit. Use 30% shade cloth when temps exceed 95 °F.',
    },
  ],

  lettuce: [
    {
      name: 'Downy Mildew',
      category: 'Fungal',
      severity: 'Medium',
      thumbnail: 'Lettuce_downy_mildew',
      symptoms: 'Angular yellow spots on upper leaf surface bounded by veins. White to grey fluffy mold on undersides.',
      cause: 'Bremia lactucae — thrives in cool, moist conditions.',
      treatment: 'Remove infected leaves. Improve air circulation. Apply copper fungicide if organic methods fail.',
      prevention: 'Space plants well. Water in the morning so leaves dry by evening. Choose resistant varieties.',
    },
    {
      name: 'Tip Burn',
      category: 'Environmental',
      severity: 'Low',
      thumbnail: 'Lettuce_tipburn',
      symptoms: 'Brown, papery edges on inner or outer leaf tips. Affects fast-growing heads most.',
      cause: 'Calcium deficiency in rapidly growing leaf tissue — triggered by heat, irregular watering, or excess nitrogen.',
      treatment: 'Water consistently. Reduce nitrogen fertilizer. Harvest in the morning when temps are cooler.',
      prevention: 'Grow in partial shade during warm months. Choose heat-tolerant varieties. Mulch to even moisture.',
    },
    {
      name: 'Bolting',
      category: 'Environmental',
      severity: 'Low',
      thumbnail: 'Lettuce_bolting',
      symptoms: 'Center stalk elongates rapidly. Leaves become bitter. Small flowers form at the top.',
      cause: 'Extended warm temperatures (above 75–80 °F) and long days trigger the flowering response.',
      treatment: 'Once bolting starts, it cannot be reversed. Harvest immediately — younger leaves may still be usable.',
      prevention: 'Plant bolt-resistant varieties. Use shade cloth. Succession-plant every 2–3 weeks for a continuous harvest window.',
    },
    {
      name: 'Slugs & Snails',
      category: 'Pest',
      severity: 'Medium',
      thumbnail: 'Lettuce_slugs',
      symptoms: 'Irregular holes chewed in leaves, especially overnight. Silvery slime trails on and around plants.',
      cause: 'Slugs and snails — active at night and in moist conditions.',
      treatment: 'Set beer traps (shallow dish of beer sunk into soil). Sprinkle iron phosphate bait (safe for pets). Hand-pick at night with a flashlight.',
      prevention: 'Remove hiding spots (boards, debris). Use copper tape around containers. Water in the morning so soil is drier at night.',
    },
  ],

  kale: [
    {
      name: 'Black Rot',
      category: 'Bacterial',
      severity: 'High',
      thumbnail: 'Kale_black_rot',
      symptoms: 'V-shaped yellow to brown lesions starting at leaf edges. Veins within the lesion turn black. Leaves wilt and drop.',
      cause: 'Xanthomonas campestris pv. campestris — enters through leaf pores, spreads by rain and irrigation.',
      treatment: 'Remove and destroy infected leaves and plants. Apply copper bactericide. Do not compost infected material.',
      prevention: 'Use disease-free seed. Rotate brassicas on a 3-year cycle. Avoid overhead watering.',
    },
    {
      name: 'Clubroot',
      category: 'Fungal',
      severity: 'High',
      thumbnail: 'Kale_clubroot',
      symptoms: 'Wilting during the day, recovering at night. Yellowing leaves. Swollen, distorted, club-shaped roots when pulled up.',
      cause: 'Plasmodiophora brassicae — soil-borne pathogen that thrives in acidic, wet soil.',
      treatment: 'No effective treatment once established. Remove and destroy infected plants. Raise soil pH to 7.0+ with lime.',
      prevention: 'Test and lime soil before planting (target pH 7.0–7.2). Rotate crops. Improve drainage.',
    },
    {
      name: 'Cabbage Worms',
      category: 'Pest',
      severity: 'Medium',
      thumbnail: 'Kale_cabbage_worm',
      symptoms: 'Irregular holes in leaves. Green caterpillars (up to 1 in) on leaf surfaces. Dark green frass pellets.',
      cause: 'Imported cabbageworm (Pieris rapae) — white butterflies lay single yellow eggs on leaf undersides.',
      treatment: 'Hand-pick caterpillars. Apply Bt (Bacillus thuringiensis var. kurstaki) spray every 5–7 days. Use floating row cover.',
      prevention: 'Cover with lightweight row cover immediately after planting. Inspect leaves weekly for eggs. Companion-plant with thyme or dill to attract predatory wasps.',
    },
    {
      name: 'Aphids',
      category: 'Pest',
      severity: 'Low',
      thumbnail: 'Kale_aphids',
      symptoms: 'Dense colonies of grey-green cabbage aphids on leaf undersides and growing tips. Curling, yellowing leaves. Sticky honeydew.',
      cause: 'Brevicoryne brassicae (cabbage aphid) — especially prolific in cool, dry weather.',
      treatment: 'Blast with a strong water spray. Apply insecticidal soap. Release ladybugs or lacewings.',
      prevention: 'Interplant with nasturtiums (trap crop) or strong herbs like oregano. Inspect regularly.',
    },
  ],

  carrots: [
    {
      name: 'Alternaria Leaf Blight',
      category: 'Fungal',
      severity: 'Medium',
      thumbnail: 'Carrot_alternaria',
      symptoms: 'Dark brown to black lesions on leaf edges and petioles. Leaves curl and die back from the tips. Weakens the root below.',
      cause: 'Alternaria dauci — favored by warm, humid weather and overhead watering.',
      treatment: 'Remove infected foliage. Apply copper-based fungicide. Ensure good air circulation.',
      prevention: 'Use disease-free seed. Rotate crops. Water at the base.',
    },
    {
      name: 'Carrot Rust Fly',
      category: 'Pest',
      severity: 'High',
      thumbnail: 'Carrot_rust_fly',
      symptoms: 'Rusty brown tunnels in the outer root. Wilted, reddish-purple tops. Roots may be stunted or forked.',
      cause: 'Larvae of Psila rosae — adults lay eggs at the base of carrot plants, larvae burrow into roots.',
      treatment: 'Harvest immediately when damage is found. There is no treatment for larvae already in roots.',
      prevention: 'Cover with fine mesh row cover (1mm or smaller) from sowing to harvest. Delay sowing until June to avoid first generation. Companion-plant with onions or leeks.',
    },
    {
      name: 'Cavity Spot',
      category: 'Fungal',
      severity: 'Low',
      thumbnail: 'Carrot_cavity_spot',
      symptoms: 'Oval, horizontal, sunken lesions on the root surface. Lesions are shallow (cosmetic damage) but can allow secondary rot.',
      cause: 'Pythium species — favored by wet soil and poor drainage.',
      treatment: 'Improve drainage. Harvest promptly once mature. Affected carrots are safe to eat — cut away damaged areas.',
      prevention: 'Plant in well-drained, loose soil. Avoid overwatering. Add compost to improve soil structure.',
    },
    {
      name: 'Forked / Misshapen Roots',
      category: 'Environmental',
      severity: 'Low',
      thumbnail: 'Carrot_forked',
      symptoms: 'Roots split, fork, or grow in twisted shapes. May be stunted.',
      cause: 'Rocky or compacted soil, fresh manure, or root-knot nematodes. Transplanting also causes forking.',
      treatment: 'Carrots are still edible — just harder to peel. Improve soil for the next planting.',
      prevention: 'Prepare deep, loose, stone-free soil (12+ in). Never transplant carrots. Use aged compost only.',
    },
  ],

  'sugar-snaps': [
    {
      name: 'Powdery Mildew',
      category: 'Fungal',
      severity: 'Medium',
      thumbnail: 'Pea_powdery_mildew',
      symptoms: 'White powdery coating on leaves, stems, and pods. Leaves yellow and dry out. Reduced pod quality.',
      cause: 'Erysiphe pisi — favored by warm days, cool nights, and poor air circulation.',
      treatment: 'Remove heavily affected leaves. Apply neem oil or baking soda spray (1 tbsp per gallon). Improve airflow around plants.',
      prevention: 'Plant resistant varieties. Space plants generously on the trellis. Avoid late-season planting when conditions favor mildew.',
    },
    {
      name: 'Fusarium Wilt',
      category: 'Fungal',
      severity: 'High',
      thumbnail: 'Pea_fusarium_wilt',
      symptoms: 'Lower leaves yellow and wilt, progressing upward. One side of the plant may wilt first. Stunted growth, often fatal.',
      cause: 'Fusarium oxysporum f. sp. pisi — soil-borne, persists in soil for years.',
      treatment: 'No chemical cure. Remove and destroy infected plants. Solarize soil in summer (cover with clear plastic for 4–6 weeks).',
      prevention: 'Plant resistant varieties (check for "Fwn" or "Fw" designation). Rotate legumes on a 4+ year cycle.',
    },
    {
      name: 'Pea Aphid',
      category: 'Pest',
      severity: 'Low',
      thumbnail: 'Pea_aphid',
      symptoms: 'Large (1/8 in), bright green aphids clustered on stems, flowers, and developing pods. Sticky honeydew. Distorted growth.',
      cause: 'Acyrthosiphon pisum — migrates from alfalfa and clover in spring.',
      treatment: 'Spray with strong water jet. Apply insecticidal soap. Encourage ladybugs and lacewings.',
      prevention: 'Avoid excess nitrogen fertilizer (promotes soft growth aphids love). Inspect plants weekly from flowering onward.',
    },
    {
      name: 'Root Rot',
      category: 'Fungal',
      severity: 'Medium',
      thumbnail: 'Pea_root_rot',
      symptoms: 'Yellowing lower leaves. Stunted growth. Roots are brown, mushy, or water-soaked when pulled up.',
      cause: 'Pythium, Rhizoctonia, or Fusarium species — caused by waterlogged or compacted soil.',
      treatment: 'Improve drainage immediately. Remove dying plants to prevent spread. Reduce watering frequency.',
      prevention: 'Plant in well-drained soil or raised beds. Avoid overwatering. Inoculate seed with Rhizobium for stronger root systems.',
    },
  ],

  'swiss-chard': [
    {
      name: 'Cercospora Leaf Spot',
      category: 'Fungal',
      severity: 'Medium',
      thumbnail: 'Chard_cercospora',
      symptoms: 'Circular tan to grey spots (1/8–1/4 in) with dark purple-brown borders on leaves. Spots may merge, causing large dead areas.',
      cause: 'Cercospora beticola — spread by rain splash, wind, and contaminated seed. Favored by warm, humid weather.',
      treatment: 'Remove spotted leaves. Apply copper fungicide or neem oil. Improve airflow around plants.',
      prevention: 'Rotate crops (avoid planting chard, beets, or spinach in the same spot). Use drip irrigation. Space plants generously.',
    },
    {
      name: 'Downy Mildew',
      category: 'Fungal',
      severity: 'Medium',
      thumbnail: 'Chard_downy_mildew',
      symptoms: 'Yellow or light green patches on upper leaf surfaces. Grey-purple fuzzy growth on undersides. Leaves curl and die.',
      cause: 'Peronospora farinosa f. sp. betae — thrives in cool, humid conditions.',
      treatment: 'Remove infected leaves. Apply copper spray. Ensure good air circulation and avoid evening watering.',
      prevention: 'Water at the base. Space plants well. Choose resistant varieties when available.',
    },
    {
      name: 'Leaf Miners',
      category: 'Pest',
      severity: 'Low',
      thumbnail: 'Chard_leaf_miner',
      symptoms: 'Winding, whitish-tan "trails" or blotchy tunnels between leaf surfaces. Leaves become papery in mined areas.',
      cause: 'Larvae of Pegomya hyoscyami — adult flies lay eggs on leaf undersides; larvae tunnel into leaves.',
      treatment: 'Remove and destroy affected leaves (do not compost). Squish visible larvae inside leaf tunnels. Apply spinosad if infestation is heavy.',
      prevention: 'Cover with floating row cover from planting. Remove lamb\'s-quarters and other weedy host plants nearby.',
    },
    {
      name: 'Slugs & Snails',
      category: 'Pest',
      severity: 'Low',
      thumbnail: 'Chard_slugs',
      symptoms: 'Large, irregular holes in leaves, especially near the soil line. Silvery slime trails on leaves and soil.',
      cause: 'Common garden slugs and snails — active at night and after rain.',
      treatment: 'Hand-pick at dusk. Set beer traps. Apply iron phosphate bait (pet-safe).',
      prevention: 'Water in the morning. Remove debris and hiding spots. Use copper tape on containers.',
    },
  ],
}

// Flat list of all category types for filtering
export const DISEASE_CATEGORIES = [
  'Fungal',
  'Bacterial',
  'Viral',
  'Pest',
  'Nutrient',
  'Environmental',
]
