export const PLANTS = [
  {
    id: 'tomato',
    name: 'Tomato',
    emoji: '🍅',
    type: 'warm',
    difficulty: 'Moderate',
    minTempF: 50,
    idealTempRange: [65, 85],
    indoorStartWeeks: 6,
    weeksAfterLastFrost: 2,
    daysToHarvest: 70,
    vessel: 'Large container (5+ gal) or in-ground',
    companions: ['Basil', 'Kale', 'Carrots'],
    avoid: ['Fennel'],
    plantMonths: [3, 4, 5, 6],
    description: 'The summer garden staple. Needs full sun, consistent water, and support staking.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 1, notes: 'Keep soil consistently moist but not waterlogged. Water gently at the base to avoid disturbing shallow roots.' },
      juvenile: { frequencyDays: 2, depthInches: 1.5, notes: 'Water deeply every 2 days to encourage strong root development. Allow top inch of soil to dry between waterings.' },
      established: { frequencyDays: 3, depthInches: 2, notes: 'Deep water 2-3 times per week. Aim for 1-2 inches of water per week total. Consistent moisture prevents blossom-end rot.' },
      method: 'Water at the base of the plant, never overhead. Use drip irrigation or a soaker hose when possible. Water in the early morning.',
      mulchAdvice: 'Apply 2-4 inches of organic mulch (straw, hay, or bark chips) 5 weeks after transplanting to retain moisture and keep soil cool.',
      containerNote: 'Containers dry out faster — check soil daily and water when top inch is dry. May need daily watering in hot weather.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/tomatoes' },
        { name: 'UMN Extension', url: 'https://extension.umn.edu/vegetables/growing-tomatoes' },
        { name: 'Gardening Know How', url: 'https://www.gardeningknowhow.com/edible/vegetables/tomato/watering-tomato-plants.htm' },
      ],
    },
  },
  {
    id: 'basil',
    name: 'Basil',
    emoji: '🌿',
    type: 'warm',
    difficulty: 'Easy',
    minTempF: 55,
    idealTempRange: [70, 90],
    indoorStartWeeks: 4,
    weeksAfterLastFrost: 2,
    daysToHarvest: 25,
    vessel: 'Small pot (1+ gal) or window box',
    companions: ['Tomato', 'Zucchini', 'Bell Pepper'],
    avoid: ['Sage'],
    plantMonths: [4, 5, 6, 7],
    description: 'Thrives in heat. Plant near tomatoes for pest deterrence and great flavor pairing.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 0.5, notes: 'Keep soil evenly moist. Mist gently to avoid displacing tiny seeds. Never let soil dry out completely.' },
      juvenile: { frequencyDays: 1, depthInches: 0.5, notes: 'Water daily, especially in warm weather. Basil likes moisture but not soggy roots.' },
      established: { frequencyDays: 2, depthInches: 1, notes: 'Water deeply when top inch of soil is dry. Basil wilts quickly when thirsty but recovers fast with a good drink.' },
      method: 'Water at the base of the plant in the morning. Avoid wetting leaves to prevent fungal diseases like downy mildew.',
      mulchAdvice: 'Apply 2-3 inches of compost or ground leaves around plants to retain soil moisture and minimize weeds.',
      containerNote: 'Small pots dry out quickly — check daily. Basil in containers may need watering twice daily in peak summer heat.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/basil' },
        { name: 'Gardening Know How', url: 'https://www.gardeningknowhow.com/edible/herbs/basil/how-to-grow-basil-plants.htm' },
      ],
    },
  },
  {
    id: 'zucchini',
    name: 'Zucchini',
    emoji: '🥒',
    type: 'warm',
    difficulty: 'Easy',
    minTempF: 60,
    idealTempRange: [70, 95],
    indoorStartWeeks: 3,
    weeksAfterLastFrost: 2,
    daysToHarvest: 50,
    vessel: 'Large container (10+ gal) or in-ground',
    companions: ['Basil', 'Lettuce', 'Bush Beans'],
    avoid: ['Potato'],
    plantMonths: [4, 5, 6, 7],
    description: 'Incredibly productive. Harvest frequently to encourage more fruit.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 1, notes: 'Keep soil consistently moist around young plants. Water gently to avoid disturbing shallow roots.' },
      juvenile: { frequencyDays: 2, depthInches: 1.5, notes: 'Water deeply every 2 days. Squash have large leaves that lose moisture quickly through transpiration.' },
      established: { frequencyDays: 3, depthInches: 2, notes: 'Provide 1-2 inches of water per week. Deep, infrequent watering encourages deep root growth.' },
      method: 'Water at soil level, avoiding the leaves. Wet foliage promotes powdery mildew, which squash are very susceptible to.',
      mulchAdvice: 'Mulch heavily with straw or wood chips to retain moisture and keep fruit clean off the soil.',
      containerNote: 'Large containers (10+ gal) are essential. Water daily in hot weather — squash are heavy drinkers.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/zucchini' },
        { name: 'UMN Extension', url: 'https://extension.umn.edu/vegetables/growing-squash' },
      ],
    },
  },
  {
    id: 'bush-beans',
    name: 'Bush Beans',
    emoji: '🫘',
    type: 'warm',
    difficulty: 'Easy',
    minTempF: 60,
    idealTempRange: [65, 85],
    indoorStartWeeks: null,
    weeksAfterLastFrost: 2,
    daysToHarvest: 55,
    vessel: 'Medium container (3+ gal) or in-ground',
    companions: ['Carrots', 'Zucchini', 'Swiss Chard'],
    avoid: ['Onion', 'Fennel'],
    plantMonths: [4, 5, 6, 7],
    description: 'Direct sow only — no transplanting needed. No staking. Perfect for beginners.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 0.5, notes: 'Keep soil moist until seeds germinate (5-10 days). Water gently to avoid washing seeds away.' },
      juvenile: { frequencyDays: 2, depthInches: 1, notes: 'Water deeply every 2 days. Beans need consistent moisture during flowering and pod development.' },
      established: { frequencyDays: 3, depthInches: 1, notes: 'About 1 inch of water per week. Avoid overhead watering to prevent bean rust and other fungal diseases.' },
      method: 'Water at the base using drip irrigation or a soaker hose. Avoid wetting foliage, especially in the evening.',
      mulchAdvice: 'Apply 2-3 inches of straw mulch after plants are 4 inches tall to conserve moisture and suppress weeds.',
      containerNote: 'Containers need consistent moisture — check every 1-2 days. Beans in pots may need daily watering in summer.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/green-beans' },
        { name: 'UMN Extension', url: 'https://extension.umn.edu/vegetables/growing-green-beans' },
      ],
    },
  },
  {
    id: 'bell-pepper',
    name: 'Bell Pepper',
    emoji: '🫑',
    type: 'warm',
    difficulty: 'Moderate',
    minTempF: 55,
    idealTempRange: [70, 90],
    indoorStartWeeks: 8,
    weeksAfterLastFrost: 2,
    daysToHarvest: 75,
    vessel: 'Medium container (3+ gal) or in-ground',
    companions: ['Basil', 'Tomato', 'Carrots'],
    avoid: ['Fennel'],
    plantMonths: [4, 5, 6],
    description: 'Start early indoors — peppers love a long warm season. Keep soil consistently moist.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 0.5, notes: 'Keep soil evenly moist. Pepper seedlings are delicate — water gently and consistently.' },
      juvenile: { frequencyDays: 2, depthInches: 1, notes: 'Water deeply every 2 days. Peppers need consistent moisture to set fruit properly.' },
      established: { frequencyDays: 2, depthInches: 1.5, notes: 'About 1-2 inches per week. Inconsistent watering causes blossom drop and blossom-end rot.' },
      method: 'Water at the base in the morning. Avoid overhead watering to prevent fungal leaf diseases.',
      mulchAdvice: 'Mulch with 2-3 inches of straw or compost to keep roots cool and soil moist.',
      containerNote: 'Peppers in containers need frequent watering — check daily. Consistent moisture is critical for fruit development.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/bell-peppers' },
        { name: 'Gardening Know How', url: 'https://www.gardeningknowhow.com/edible/vegetables/pepper/watering-pepper-plants.htm' },
      ],
    },
  },
  {
    id: 'lettuce',
    name: 'Lettuce',
    emoji: '🥬',
    type: 'cool',
    difficulty: 'Easy',
    minTempF: 40,
    idealTempRange: [45, 75],
    indoorStartWeeks: 4,
    weeksAfterLastFrost: 0,
    daysToHarvest: 30,
    vessel: 'Shallow container (6+ in deep) or window box',
    companions: ['Carrots', 'Tomato', 'Sugar Snaps'],
    avoid: ['Celery'],
    plantMonths: [1, 2, 3, 9, 10, 11],
    description: 'Cool-season superstar. In Zone 9b, plant spring and fall. Bolts in summer heat.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 0.5, notes: 'Keep soil consistently moist. Mist gently — lettuce seeds need light and moisture to germinate.' },
      juvenile: { frequencyDays: 1, depthInches: 0.5, notes: 'Water daily to keep shallow roots hydrated. Lettuce wilts fast when thirsty but recovers quickly.' },
      established: { frequencyDays: 2, depthInches: 1, notes: 'About 1 inch of water per week. Consistent moisture prevents bitter leaves and delays bolting.' },
      method: 'Water at the base or use overhead misting in hot weather to cool plants and slow transpiration. Morning watering is best.',
      mulchAdvice: 'Apply organic mulch to keep soil cool and moist — this helps prevent premature bolting in warm weather.',
      containerNote: 'Shallow containers dry out fast — check daily. Lettuce has shallow roots and dries out quickly.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/lettuce' },
        { name: 'UMN Extension', url: 'https://extension.umn.edu/vegetables/growing-lettuce' },
      ],
    },
  },
  {
    id: 'kale',
    name: 'Kale',
    emoji: '🥦',
    type: 'cool',
    difficulty: 'Easy',
    minTempF: 35,
    idealTempRange: [45, 75],
    indoorStartWeeks: 4,
    weeksAfterLastFrost: 0,
    daysToHarvest: 60,
    vessel: 'Medium container (3+ gal) or in-ground',
    companions: ['Bush Beans', 'Carrots', 'Sugar Snaps'],
    avoid: ['Tomato', 'Strawberry'],
    plantMonths: [1, 2, 3, 9, 10, 11],
    description: 'Hardy and frost-tolerant. In Zone 9b, kale can grow nearly year-round.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 0.5, notes: 'Keep soil evenly moist for germination and early growth. Water gently to avoid soil compaction.' },
      juvenile: { frequencyDays: 2, depthInches: 1, notes: 'Water deeply every 2 days. Kale prefers consistently moist soil but tolerates brief dry spells.' },
      established: { frequencyDays: 2, depthInches: 1, notes: 'About 1-1.5 inches per week. Consistent moisture produces the most tender, least bitter leaves.' },
      method: 'Water at the base. Avoid overhead watering in humid conditions to prevent fungal issues.',
      mulchAdvice: 'Mulch with 2-3 inches of straw or compost to maintain cool, moist soil conditions.',
      containerNote: 'Medium containers need regular watering — every 1-2 days depending on temperature.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/kale' },
        { name: 'UMN Extension', url: 'https://extension.umn.edu/vegetables/growing-kale' },
      ],
    },
  },
  {
    id: 'carrots',
    name: 'Carrots',
    emoji: '🥕',
    type: 'cool',
    difficulty: 'Moderate',
    minTempF: 40,
    idealTempRange: [60, 75],
    indoorStartWeeks: null,
    weeksAfterLastFrost: 0,
    daysToHarvest: 75,
    vessel: 'Deep container (12+ in) or in-ground',
    companions: ['Lettuce', 'Kale', 'Tomato'],
    avoid: ['Dill', 'Fennel'],
    plantMonths: [1, 2, 3, 9, 10],
    description: 'Direct sow only — carrots hate being transplanted. Needs deep, loose, rock-free soil.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 0.5, notes: 'Keep soil surface consistently moist — carrot seeds are slow to germinate (10-21 days) and must not dry out.' },
      juvenile: { frequencyDays: 2, depthInches: 1, notes: 'Water deeply every 2 days to encourage roots to grow downward. Shallow watering produces forked carrots.' },
      established: { frequencyDays: 3, depthInches: 1.5, notes: 'About 1 inch per week. Deep, even watering prevents cracking and produces smooth, sweet roots.' },
      method: 'Water gently at soil level. Overhead watering is fine for seedlings but switch to base watering as plants mature.',
      mulchAdvice: 'Mulch lightly after seedlings emerge to retain moisture and keep soil cool. Avoid heavy mulch that prevents emergence.',
      containerNote: 'Deep containers (12+ in) are essential. Water evenly — inconsistent moisture causes cracked or forked roots.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/carrots' },
        { name: 'UMN Extension', url: 'https://extension.umn.edu/vegetables/growing-carrots' },
      ],
    },
  },
  {
    id: 'sugar-snaps',
    name: 'Sugar Snaps',
    emoji: '🫛',
    type: 'cool',
    difficulty: 'Easy',
    minTempF: 40,
    idealTempRange: [55, 75],
    indoorStartWeeks: null,
    weeksAfterLastFrost: 0,
    daysToHarvest: 60,
    vessel: 'Medium container (3+ gal) with trellis or cage',
    companions: ['Lettuce', 'Carrots', 'Swiss Chard'],
    avoid: ['Onion', 'Garlic'],
    plantMonths: [1, 2, 3, 9, 10],
    description: 'Sweet, crisp, and easy. Direct sow in cool weather. Needs a trellis to climb.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 0.5, notes: 'Keep soil moist until seeds germinate. Pea seeds benefit from soaking overnight before planting.' },
      juvenile: { frequencyDays: 2, depthInches: 1, notes: 'Water deeply every 2 days. Peas need consistent moisture during flowering for good pod set.' },
      established: { frequencyDays: 3, depthInches: 1, notes: 'About 1 inch per week. Increase watering during flowering and pod development for sweet, plump pods.' },
      method: 'Water at the base. Avoid overhead watering during flowering to prevent blossom drop.',
      mulchAdvice: 'Mulch with 2 inches of straw to keep roots cool and moist, especially as temperatures rise.',
      containerNote: 'Containers with trellises need regular watering — the trellis structure can increase wind exposure and drying.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/peas' },
        { name: 'Gardening Know How', url: 'https://www.gardeningknowhow.com/edible/vegetables/peas/watering-pea-plants.htm' },
      ],
    },
  },
  {
    id: 'swiss-chard',
    name: 'Swiss Chard',
    emoji: '🌱',
    type: 'cool',
    difficulty: 'Easy',
    minTempF: 40,
    idealTempRange: [50, 80],
    indoorStartWeeks: 4,
    weeksAfterLastFrost: 0,
    daysToHarvest: 55,
    vessel: 'Medium container (3+ gal) or in-ground',
    companions: ['Bush Beans', 'Carrots', 'Sugar Snaps'],
    avoid: ['Corn'],
    plantMonths: [1, 2, 3, 8, 9, 10, 11],
    description: 'Colorful and versatile. More heat-tolerant than lettuce. Harvest outer leaves continuously.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 0.5, notes: 'Keep soil evenly moist for germination. Chard seeds are multi-germ — thin to strongest seedling.' },
      juvenile: { frequencyDays: 2, depthInches: 1, notes: 'Water deeply every 2 days. Consistent moisture produces tender, large leaves.' },
      established: { frequencyDays: 2, depthInches: 1, notes: 'About 1-1.5 inches per week. Chard is more drought-tolerant than lettuce but tastes best with regular water.' },
      method: 'Water at the base. Morning watering is preferred to allow foliage to dry before evening.',
      mulchAdvice: 'Mulch with 2-3 inches of compost or straw to maintain even soil moisture.',
      containerNote: 'Medium containers work well. Water every 1-2 days — chard has moderate water needs.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/swiss-chard' },
        { name: 'Gardening Know How', url: 'https://www.gardeningknowhow.com/edible/vegetables/swiss-chard/growing-swiss-chard.htm' },
      ],
    },
  },
  {
    id: 'thyme',
    name: 'Thyme',
    emoji: '🌿',
    type: 'warm',
    difficulty: 'Easy',
    minTempF: 30,
    idealTempRange: [60, 80],
    indoorStartWeeks: 8,
    weeksAfterLastFrost: 0,
    daysToHarvest: 90,
    vessel: 'Small pot (1+ gal) or herb garden',
    companions: ['Tomato', 'Eggplant', 'Lavender'],
    avoid: ['Basil'],
    plantMonths: [3, 4, 5, 9, 10],
    description: 'Drought-tolerant perennial herb. Thrives in well-drained soil and full sun. Trim regularly to keep bushy.',
    watering: {
      seedling: { frequencyDays: 2, depthInches: 0.5, notes: 'Keep soil lightly moist but never soggy. Thyme seedlings are prone to damping off in wet conditions.' },
      juvenile: { frequencyDays: 3, depthInches: 0.5, notes: 'Allow soil to dry between waterings. Thyme prefers drier conditions than most herbs.' },
      established: { frequencyDays: 7, depthInches: 0.5, notes: 'Water only when soil is dry. Established thyme is very drought-tolerant and prefers to stay on the dry side.' },
      method: 'Water at the base. Excellent drainage is essential — thyme hates wet feet. Consider adding perlite or sand to soil.',
      mulchAdvice: 'Use gravel or stone mulch rather than organic mulch to improve drainage and prevent crown rot.',
      containerNote: 'Ensure pots have excellent drainage. Terracotta pots are ideal as they wick away excess moisture.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/thyme' },
        { name: 'Gardening Know How', url: 'https://www.gardeningknowhow.com/edible/herbs/thyme/growing-thyme.htm' },
      ],
    },
  },
  {
    id: 'parsley',
    name: 'Parsley',
    emoji: '🌿',
    type: 'cool',
    difficulty: 'Easy',
    minTempF: 40,
    idealTempRange: [50, 75],
    indoorStartWeeks: 6,
    weeksAfterLastFrost: 0,
    daysToHarvest: 70,
    vessel: 'Small pot (1+ gal) or window box',
    companions: ['Tomato', 'Carrots', 'Lettuce'],
    avoid: ['Mint'],
    plantMonths: [2, 3, 4, 9, 10, 11],
    description: 'Slow to germinate (2-4 weeks) — be patient. Biennial that grows well in Zone 9b fall through spring.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 0.5, notes: 'Keep soil consistently moist during the long germination period (14-28 days). Never let soil crust over.' },
      juvenile: { frequencyDays: 1, depthInches: 0.5, notes: 'Water daily to keep soil evenly moist. Parsley likes more moisture than most herbs.' },
      established: { frequencyDays: 2, depthInches: 1, notes: 'About 1 inch per week. Parsley likes consistently moist soil — more like a vegetable than a typical herb.' },
      method: 'Water at the base in the morning. Parsley tolerates overhead watering better than many herbs.',
      mulchAdvice: 'Mulch with 2 inches of compost to keep soil moist and cool.',
      containerNote: 'Keep container soil consistently moist. Parsley has a deep taproot — use a pot at least 8 inches deep.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/parsley' },
        { name: 'Gardening Know How', url: 'https://www.gardeningknowhow.com/edible/herbs/parsley/how-to-grow-parsley.htm' },
      ],
    },
  },
  {
    id: 'radishes',
    name: 'Radishes',
    emoji: '🔴',
    type: 'cool',
    difficulty: 'Easy',
    minTempF: 40,
    idealTempRange: [50, 65],
    indoorStartWeeks: null,
    weeksAfterLastFrost: 0,
    daysToHarvest: 25,
    vessel: 'Shallow container (6+ in deep) or in-ground',
    companions: ['Carrots', 'Lettuce', 'Peas'],
    avoid: ['Hyssop'],
    plantMonths: [1, 2, 3, 9, 10, 11],
    description: 'One of the fastest crops from seed to harvest. Direct sow every 2 weeks for continuous supply. Bolts quickly in heat.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 0.5, notes: 'Keep soil evenly moist for quick germination (3-7 days). Radishes grow fast and need steady water from day one.' },
      juvenile: { frequencyDays: 1, depthInches: 0.5, notes: 'Water daily to promote rapid, even growth. Inconsistent watering makes radishes woody and pithy.' },
      established: { frequencyDays: 2, depthInches: 1, notes: 'About 1 inch per week. Even moisture is critical — uneven watering causes cracking and hot, pungent flavor.' },
      method: 'Water gently at soil level. Radishes have shallow roots and respond quickly to both over and under watering.',
      mulchAdvice: 'Light mulch helps retain moisture but keep it thin so radish shoulders can push through the soil surface.',
      containerNote: 'Shallow containers work fine but dry out fast. Check and water daily for the best, mildest radishes.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/radishes' },
        { name: 'Gardening Know How', url: 'https://www.gardeningknowhow.com/edible/vegetables/radish/growing-radishes.htm' },
      ],
    },
  },
  {
    id: 'onions',
    name: 'Long Day Onions',
    emoji: '🧅',
    type: 'cool',
    difficulty: 'Moderate',
    minTempF: 35,
    idealTempRange: [55, 75],
    indoorStartWeeks: 8,
    weeksAfterLastFrost: 0,
    daysToHarvest: 100,
    vessel: 'Medium container (3+ gal, 6+ in deep) or in-ground',
    companions: ['Carrots', 'Lettuce', 'Tomato'],
    avoid: ['Peas', 'Bush Beans'],
    plantMonths: [1, 2, 3],
    description: 'Long day varieties need 14-16 hrs of daylight to bulb. Start from seed indoors in winter for spring transplant. Cure after harvest.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 0.5, notes: 'Keep soil consistently moist for thin, grass-like seedlings. They have very shallow roots at this stage.' },
      juvenile: { frequencyDays: 2, depthInches: 1, notes: 'Water deeply every 2 days. Onions need consistent moisture during leaf growth and early bulb formation.' },
      established: { frequencyDays: 3, depthInches: 1, notes: 'About 1 inch per week. Reduce watering when tops begin to fall over — this signals bulbs are maturing.' },
      method: 'Water at the base. Avoid overhead watering to prevent fungal diseases on the hollow leaves.',
      mulchAdvice: 'Mulch lightly with straw to retain moisture and suppress weeds. Keep mulch away from bulb tops.',
      containerNote: 'Ensure containers are at least 6 inches deep for bulb development. Water regularly — onions have shallow roots.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/onions' },
        { name: 'UMN Extension', url: 'https://extension.umn.edu/vegetables/growing-onions' },
      ],
    },
  },
  {
    id: 'poblano-pepper',
    name: 'Poblano Pepper',
    emoji: '🌶️',
    type: 'warm',
    difficulty: 'Moderate',
    minTempF: 55,
    idealTempRange: [70, 85],
    indoorStartWeeks: 8,
    weeksAfterLastFrost: 2,
    daysToHarvest: 75,
    vessel: 'Medium container (5+ gal) or in-ground',
    companions: ['Basil', 'Tomato', 'Carrots'],
    avoid: ['Fennel'],
    plantMonths: [4, 5, 6],
    description: 'Mild, rich-flavored pepper — perfect for stuffing. Dries into ancho chilis. Needs warm soil and consistent water.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 0.5, notes: 'Keep soil evenly moist. Pepper seedlings are slow to establish and need consistent warmth and moisture.' },
      juvenile: { frequencyDays: 2, depthInches: 1, notes: 'Water deeply every 2 days. Consistent moisture helps plants develop strong root systems before fruiting.' },
      established: { frequencyDays: 2, depthInches: 1.5, notes: 'About 1-2 inches per week. Poblanos need steady water for large, thick-walled fruit development.' },
      method: 'Water at the base in the morning. Avoid wetting foliage to prevent bacterial leaf spot.',
      mulchAdvice: 'Mulch with 2-3 inches of straw or compost to maintain warm, moist soil.',
      containerNote: 'Use 5+ gallon containers. Water daily in hot weather — pepper fruit development demands consistent moisture.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/bell-peppers' },
        { name: 'Gardening Know How', url: 'https://www.gardeningknowhow.com/edible/vegetables/pepper/growing-poblano-peppers.htm' },
      ],
    },
  },
  {
    id: 'shishito-pepper',
    name: 'Shishito Pepper',
    emoji: '🌶️',
    type: 'warm',
    difficulty: 'Easy',
    minTempF: 55,
    idealTempRange: [70, 85],
    indoorStartWeeks: 8,
    weeksAfterLastFrost: 2,
    daysToHarvest: 60,
    vessel: 'Medium container (3+ gal) or in-ground',
    companions: ['Basil', 'Tomato', 'Marigolds'],
    avoid: ['Fennel'],
    plantMonths: [4, 5, 6],
    description: 'Prolific producer of thin-walled, mild peppers. Pick when green and blister in a hot pan. 1 in 10 is spicy!',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 0.5, notes: 'Keep soil consistently moist. Shishito seedlings need warmth and even moisture to thrive.' },
      juvenile: { frequencyDays: 2, depthInches: 1, notes: 'Water deeply every 2 days. Good moisture promotes the prolific fruiting shishitos are known for.' },
      established: { frequencyDays: 2, depthInches: 1, notes: 'About 1-2 inches per week. Consistent watering keeps thin-walled peppers from becoming overly spicy.' },
      method: 'Water at the base in the morning. Shishitos are relatively disease-resistant but still benefit from dry foliage.',
      mulchAdvice: 'Apply 2-3 inches of organic mulch to retain moisture and keep roots warm.',
      containerNote: 'Excellent container plants. Water daily in hot weather — the prolific fruiting increases water demand.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/bell-peppers' },
        { name: 'Gardening Know How', url: 'https://www.gardeningknowhow.com/edible/vegetables/pepper/watering-pepper-plants.htm' },
      ],
    },
  },
  {
    id: 'thai-chili',
    name: 'Thai Chili',
    emoji: '🌶️',
    type: 'warm',
    difficulty: 'Moderate',
    minTempF: 60,
    idealTempRange: [75, 90],
    indoorStartWeeks: 10,
    weeksAfterLastFrost: 3,
    daysToHarvest: 80,
    vessel: 'Medium container (3+ gal) or in-ground',
    companions: ['Basil', 'Tomato', 'Marigolds'],
    avoid: ['Fennel'],
    plantMonths: [4, 5, 6],
    description: 'Compact plants loaded with small, fiery peppers (50,000-100,000 SHU). Ornamental and edible. Loves Zone 9b summers.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 0.5, notes: 'Keep soil warm and moist. Hot peppers are slow to germinate — patience and consistent moisture are key.' },
      juvenile: { frequencyDays: 2, depthInches: 1, notes: 'Water deeply every 2 days. Allow slight drying between waterings to encourage heat development in peppers.' },
      established: { frequencyDays: 3, depthInches: 1, notes: 'About 1 inch per week. Mild water stress can increase capsaicin levels (spiciness) in hot peppers.' },
      method: 'Water at the base. Thai chilis are compact plants that handle heat well but still need consistent moisture.',
      mulchAdvice: 'Mulch with 2 inches of straw to retain heat and moisture around these heat-loving plants.',
      containerNote: 'Excellent in 3+ gallon containers. Let soil dry slightly between waterings for spicier peppers.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/bell-peppers' },
        { name: 'Gardening Know How', url: 'https://www.gardeningknowhow.com/edible/vegetables/pepper/growing-thai-peppers.htm' },
      ],
    },
  },
  {
    id: 'eggplant',
    name: 'Long Purple Eggplant',
    emoji: '🍆',
    type: 'warm',
    difficulty: 'Moderate',
    minTempF: 60,
    idealTempRange: [70, 85],
    indoorStartWeeks: 8,
    weeksAfterLastFrost: 3,
    daysToHarvest: 70,
    vessel: 'Large container (5+ gal) or in-ground',
    companions: ['Basil', 'Thyme', 'Marigolds'],
    avoid: ['Fennel', 'Tomato'],
    plantMonths: [4, 5, 6],
    description: 'Slender, tender Italian-style eggplant. Harvest when skin is glossy — dull skin means overripe. Loves heat and full sun.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 1, notes: 'Keep soil evenly moist and warm. Eggplant seedlings need both warmth and moisture to establish well.' },
      juvenile: { frequencyDays: 2, depthInches: 1.5, notes: 'Water deeply every 2 days. Eggplant is in the tomato family and has similar water needs.' },
      established: { frequencyDays: 2, depthInches: 2, notes: 'About 1-2 inches per week. Consistent deep watering produces glossy, tender fruit without bitterness.' },
      method: 'Water at the base in the morning. Avoid overhead watering to prevent fungal diseases common in nightshade family.',
      mulchAdvice: 'Apply 2-4 inches of organic mulch to maintain warm, moist soil. Black plastic mulch can help warm soil early in season.',
      containerNote: 'Use 5+ gallon containers. Eggplants are heavy feeders and drinkers — water daily in summer heat.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/eggplants' },
        { name: 'UMN Extension', url: 'https://extension.umn.edu/vegetables/growing-eggplant' },
      ],
    },
  },
  {
    id: 'summer-squash',
    name: 'Summer Squash',
    emoji: '🟡',
    type: 'warm',
    difficulty: 'Easy',
    minTempF: 60,
    idealTempRange: [70, 95],
    indoorStartWeeks: 3,
    weeksAfterLastFrost: 2,
    daysToHarvest: 50,
    vessel: 'Large container (10+ gal) or in-ground',
    companions: ['Basil', 'Marigolds', 'Bush Beans'],
    avoid: ['Potato'],
    plantMonths: [4, 5, 6, 7],
    description: 'Fast-growing and very productive. Harvest young (6-8 in) for best flavor. Check plants daily — they grow quickly!',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 1, notes: 'Keep soil consistently moist. Summer squash grows rapidly and needs steady water from the start.' },
      juvenile: { frequencyDays: 2, depthInches: 1.5, notes: 'Water deeply every 2 days. Large leaves lose water quickly through transpiration on hot days.' },
      established: { frequencyDays: 3, depthInches: 2, notes: 'About 1-2 inches per week. Deep watering encourages roots to grow down and improves drought tolerance.' },
      method: 'Water at soil level, keeping leaves dry. Powdery mildew thrives on wet squash foliage.',
      mulchAdvice: 'Mulch heavily with straw to retain moisture and keep developing fruit off damp soil.',
      containerNote: 'Needs very large containers (10+ gal). Water daily in hot weather — squash are extremely thirsty plants.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/summer-squash' },
        { name: 'UMN Extension', url: 'https://extension.umn.edu/vegetables/growing-squash' },
      ],
    },
  },
  {
    id: 'cucumber',
    name: 'Cucumber (Poinsett 76)',
    emoji: '🥒',
    type: 'warm',
    difficulty: 'Easy',
    minTempF: 60,
    idealTempRange: [65, 85],
    indoorStartWeeks: 3,
    weeksAfterLastFrost: 2,
    daysToHarvest: 65,
    vessel: 'Large container (5+ gal) with trellis or in-ground',
    companions: ['Lettuce', 'Peas', 'Radishes'],
    avoid: ['Potato', 'Melon'],
    plantMonths: [4, 5, 6, 7],
    description: 'Disease-resistant slicing cucumber. Poinsett 76 tolerates heat and humidity well. Trellis for straight fruit and better airflow.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 1, notes: 'Keep soil consistently moist. Cucumber seeds germinate in 3-7 days with warm, moist soil.' },
      juvenile: { frequencyDays: 2, depthInches: 1.5, notes: 'Water deeply every 2 days. Cucumbers are 95% water and need consistent moisture to develop properly.' },
      established: { frequencyDays: 2, depthInches: 2, notes: 'About 1-2 inches per week. Inconsistent watering causes bitter, misshapen fruit. Increase during fruiting.' },
      method: 'Water at the base using drip irrigation. Avoid wetting leaves to prevent downy mildew and leaf spot.',
      mulchAdvice: 'Apply 2-3 inches of straw mulch to retain moisture and keep fruit clean when growing on the ground.',
      containerNote: 'Use 5+ gallon containers with a trellis. Trellised cucumbers dry out faster from wind — check daily.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/cucumbers' },
        { name: 'Gardening Know How', url: 'https://www.gardeningknowhow.com/edible/vegetables/cucumber/watering-cucumber-plants.htm' },
      ],
    },
  },
  {
    id: 'zinnias',
    name: 'Zinnias',
    emoji: '🌸',
    type: 'warm',
    difficulty: 'Easy',
    minTempF: 55,
    idealTempRange: [70, 90],
    indoorStartWeeks: 4,
    weeksAfterLastFrost: 2,
    daysToHarvest: 60,
    vessel: 'Medium container (3+ gal) or garden bed',
    companions: ['Tomato', 'Marigolds', 'Basil'],
    avoid: [],
    plantMonths: [4, 5, 6, 7],
    description: 'Salmon Queen and multicolor mix. Cut-and-come-again flowers — the more you cut, the more they bloom. Pollinators love them.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 0.5, notes: 'Keep soil evenly moist for germination. Zinnia seeds sprout quickly (5-7 days) in warm, moist soil.' },
      juvenile: { frequencyDays: 2, depthInches: 1, notes: 'Water deeply every 2 days. Young zinnias establish quickly and benefit from consistent moisture.' },
      established: { frequencyDays: 3, depthInches: 1, notes: 'About 1 inch per week. Zinnias are fairly drought-tolerant once established but bloom better with regular water.' },
      method: 'Water at the base ONLY. Zinnias are extremely susceptible to powdery mildew — never water overhead.',
      mulchAdvice: 'Light mulch helps retain moisture. Good air circulation is more important than heavy mulching for zinnias.',
      containerNote: 'Medium containers work well. Water every 2-3 days — zinnias tolerate slight drying between waterings.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/zinnias' },
        { name: 'Gardening Know How', url: 'https://www.gardeningknowhow.com/ornamental/flowers/zinnia/growing-zinnia-flowers.htm' },
      ],
    },
  },
  {
    id: 'violas',
    name: 'Petite Violas (Fairyland)',
    emoji: '💜',
    type: 'cool',
    difficulty: 'Easy',
    minTempF: 25,
    idealTempRange: [40, 70],
    indoorStartWeeks: 8,
    weeksAfterLastFrost: 0,
    daysToHarvest: 60,
    vessel: 'Small pot (1+ gal) or window box',
    companions: ['Lettuce', 'Kale', 'Parsley'],
    avoid: [],
    plantMonths: [9, 10, 11, 1, 2],
    description: 'Dainty edible flowers — gorgeous in salads and on cakes. Extremely cold-hardy. Bloom through Zone 9b winter.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 0.5, notes: 'Keep soil consistently moist. Viola seeds are tiny and need constant moisture to germinate (10-14 days).' },
      juvenile: { frequencyDays: 2, depthInches: 0.5, notes: 'Water every 2 days to keep soil lightly moist. Violas prefer cool, moist conditions.' },
      established: { frequencyDays: 3, depthInches: 0.5, notes: 'About 1 inch per week. Violas are light drinkers — water when top inch of soil feels dry.' },
      method: 'Water at the base in the morning. Violas are fairly resistant to fungal issues but still prefer dry foliage.',
      mulchAdvice: 'Light mulch helps retain moisture and regulate soil temperature during cool-season growing.',
      containerNote: 'Small pots dry out quickly in wind. Check every 1-2 days and water when soil surface is dry.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/pansies' },
        { name: 'Gardening Know How', url: 'https://www.gardeningknowhow.com/ornamental/flowers/pansy/growing-violas.htm' },
      ],
    },
  },
  {
    id: 'french-alouette',
    name: 'Ranunculus (French Alouette)',
    emoji: '🌹',
    type: 'cool',
    difficulty: 'Moderate',
    minTempF: 25,
    idealTempRange: [45, 65],
    indoorStartWeeks: null,
    weeksAfterLastFrost: 0,
    daysToHarvest: 90,
    vessel: 'Medium container (3+ gal) or garden bed',
    companions: ['Violas', 'Lavender', 'Lettuce'],
    avoid: [],
    plantMonths: [10, 11, 12, 1],
    description: 'Plant pre-soaked corms in fall for stunning spring blooms. French Alouette series produces densely-petalled, rose-like flowers. Excellent cut flower.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 0.5, notes: 'After planting pre-soaked corms, water well and keep soil moist until shoots emerge (2-3 weeks).' },
      juvenile: { frequencyDays: 2, depthInches: 0.5, notes: 'Water every 2-3 days as foliage develops. Ranunculus like cool, moist conditions but not waterlogging.' },
      established: { frequencyDays: 3, depthInches: 0.5, notes: 'Water when top inch of soil is dry. Reduce watering after blooming finishes as foliage dies back.' },
      method: 'Water at the base. Avoid wetting the crown of the plant which can cause corm rot in wet conditions.',
      mulchAdvice: 'Light mulch helps insulate corms in cold weather and retains moisture. Avoid heavy mulch that traps moisture against corms.',
      containerNote: 'Ensure excellent drainage — ranunculus corms rot easily in soggy soil. Use well-draining potting mix.',
      sources: [
        { name: 'Gardening Know How', url: 'https://www.gardeningknowhow.com/ornamental/bulbs/ranunculus/growing-ranunculus.htm' },
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/ranunculus' },
      ],
    },
  },
  {
    id: 'lavender',
    name: 'Fernleaf Lavender',
    emoji: '💐',
    type: 'warm',
    difficulty: 'Easy',
    minTempF: 40,
    idealTempRange: [60, 80],
    indoorStartWeeks: 10,
    weeksAfterLastFrost: 2,
    daysToHarvest: 90,
    vessel: 'Medium container (3+ gal) with excellent drainage',
    companions: ['Thyme', 'Rosemary', 'Marigolds'],
    avoid: ['Mint'],
    plantMonths: [3, 4, 5],
    description: 'Fernleaf (Lavandula multifida) has lacy, fern-like foliage and blooms nearly year-round in Zone 9b. Drought-tolerant once established.',
    watering: {
      seedling: { frequencyDays: 2, depthInches: 0.5, notes: 'Keep soil lightly moist but never soggy. Lavender seedlings are vulnerable to damping off.' },
      juvenile: { frequencyDays: 4, depthInches: 0.5, notes: 'Water every 3-4 days. Begin training lavender for dry conditions by reducing watering gradually.' },
      established: { frequencyDays: 7, depthInches: 0.5, notes: 'Water only when soil is completely dry. Established lavender is very drought-tolerant and prefers dry conditions.' },
      method: 'Water at the base. Excellent drainage is absolutely essential — lavender dies from overwatering more than underwatering.',
      mulchAdvice: 'Use gravel, pebbles, or crushed stone as mulch — organic mulch retains too much moisture and can cause root rot.',
      containerNote: 'Use containers with drainage holes and fast-draining soil. Add perlite or coarse sand. Water only when completely dry.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/lavender' },
        { name: 'Gardening Know How', url: 'https://www.gardeningknowhow.com/ornamental/flowers/lavender/growing-lavender-plants.htm' },
      ],
    },
  },
  {
    id: 'marigolds',
    name: 'Marigolds',
    emoji: '🏵️',
    type: 'warm',
    difficulty: 'Easy',
    minTempF: 55,
    idealTempRange: [65, 85],
    indoorStartWeeks: 4,
    weeksAfterLastFrost: 2,
    daysToHarvest: 50,
    vessel: 'Small pot (1+ gal) or garden border',
    companions: ['Tomato', 'Basil', 'Peppers'],
    avoid: [],
    plantMonths: [4, 5, 6, 7],
    description: 'The ultimate companion plant — repels aphids, whiteflies, and nematodes. Deadhead spent blooms for continuous flowering.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 0.5, notes: 'Keep soil moist for germination. Marigold seeds sprout fast (5-7 days) and need consistent moisture early on.' },
      juvenile: { frequencyDays: 2, depthInches: 1, notes: 'Water deeply every 2 days. Young marigolds establish quickly with regular moisture.' },
      established: { frequencyDays: 3, depthInches: 1, notes: 'About 1 inch per week. Marigolds are moderately drought-tolerant but bloom best with consistent water.' },
      method: 'Water at the base. Avoid overhead watering to prevent botrytis (gray mold) on the dense flower heads.',
      mulchAdvice: 'Light mulch helps but marigolds are not fussy. They tolerate a range of soil moisture conditions.',
      containerNote: 'Small pots dry out quickly. Water every 1-2 days in summer for continuous blooming.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/marigolds' },
        { name: 'Gardening Know How', url: 'https://www.gardeningknowhow.com/ornamental/flowers/marigold/growing-marigold-flowers.htm' },
      ],
    },
  },
  {
    id: 'calabrian-chili',
    name: 'Calabrian Chili',
    emoji: '🌶️',
    type: 'warm',
    difficulty: 'Moderate',
    minTempF: 60,
    idealTempRange: [75, 90],
    indoorStartWeeks: 10,
    weeksAfterLastFrost: 3,
    daysToHarvest: 80,
    vessel: 'Medium container (3+ gal) or in-ground',
    companions: ['Basil', 'Tomato', 'Marigolds'],
    avoid: ['Fennel'],
    plantMonths: [4, 5, 6],
    description: 'Italian heirloom pepper with fruity, medium heat (25,000-40,000 SHU). Famous in Calabrian chili paste. Ripens from green to deep red.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 0.5, notes: 'Keep soil warm and moist. Like all hot peppers, Calabrian chilis are slow to germinate and need patience.' },
      juvenile: { frequencyDays: 2, depthInches: 1, notes: 'Water deeply every 2 days. Consistent moisture during early growth leads to stronger, more productive plants.' },
      established: { frequencyDays: 3, depthInches: 1, notes: 'About 1 inch per week. Slight water stress after fruit set can increase heat and concentrate flavor.' },
      method: 'Water at the base in the morning. Dry foliage helps prevent the bacterial and fungal diseases peppers are prone to.',
      mulchAdvice: 'Mulch with 2-3 inches of straw or compost to keep soil warm and conserve moisture.',
      containerNote: 'Water every 1-2 days in hot weather. Allow slight drying between waterings for more intense flavor.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/bell-peppers' },
        { name: 'Gardening Know How', url: 'https://www.gardeningknowhow.com/edible/vegetables/pepper/watering-pepper-plants.htm' },
      ],
    },
  },
  {
    id: 'bok-choy',
    name: 'Bok Choy',
    emoji: '🥬',
    type: 'cool',
    difficulty: 'Easy',
    minTempF: 35,
    idealTempRange: [45, 75],
    indoorStartWeeks: 4,
    weeksAfterLastFrost: 0,
    daysToHarvest: 45,
    vessel: 'Shallow container (6+ in deep) or in-ground',
    companions: ['Carrots', 'Lettuce', 'Onions'],
    avoid: ['Strawberry'],
    plantMonths: [2, 3, 4, 9, 10, 11],
    description: 'Fast-growing Asian green — harvest baby bok choy at 6 in or let it mature. Bolts quickly in heat, so plant in cool months.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 0.5, notes: 'Keep soil consistently moist. Bok choy germinates quickly and needs steady moisture for rapid growth.' },
      juvenile: { frequencyDays: 1, depthInches: 0.5, notes: 'Water daily to keep soil evenly moist. Bok choy grows fast and bolts if stressed by inconsistent watering.' },
      established: { frequencyDays: 2, depthInches: 1, notes: 'About 1 inch per week. Consistent moisture produces crisp, tender stems and delays bolting.' },
      method: 'Water at the base. Overhead watering is acceptable in cool weather but avoid it if temperatures are warm.',
      mulchAdvice: 'Mulch lightly to keep soil cool and moist. This helps prevent bolting in marginal temperatures.',
      containerNote: 'Shallow containers work but dry out fast. Check daily — bok choy needs consistent moisture.',
      sources: [
        { name: 'Gardening Know How', url: 'https://www.gardeningknowhow.com/edible/vegetables/bok-choy/growing-bok-choy.htm' },
        { name: 'UMN Extension', url: 'https://extension.umn.edu/vegetables/growing-asian-greens' },
      ],
    },
  },
  {
    id: 'habanero',
    name: 'Habanero',
    emoji: '🔥',
    type: 'warm',
    difficulty: 'Moderate',
    minTempF: 60,
    idealTempRange: [75, 90],
    indoorStartWeeks: 10,
    weeksAfterLastFrost: 3,
    daysToHarvest: 100,
    vessel: 'Medium container (5+ gal) or in-ground',
    companions: ['Basil', 'Tomato', 'Marigolds'],
    avoid: ['Fennel'],
    plantMonths: [4, 5, 6],
    description: 'Very hot (100,000-350,000 SHU) with fruity, tropical flavor. Start very early indoors — needs a long, warm season. Prolific once producing.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 0.5, notes: 'Keep soil warm (80-85F) and moist. Habanero seeds are slow to germinate (14-28 days) — be patient.' },
      juvenile: { frequencyDays: 2, depthInches: 1, notes: 'Water deeply every 2 days. Steady moisture during early growth builds the strong root system habaneros need.' },
      established: { frequencyDays: 3, depthInches: 1, notes: 'About 1 inch per week. Allow soil to dry slightly between waterings — mild stress increases capsaicin and heat.' },
      method: 'Water at the base in the morning. Habaneros benefit from slightly drier conditions than sweet peppers.',
      mulchAdvice: 'Mulch with 2-3 inches of organic material to maintain warm soil temperatures habaneros love.',
      containerNote: 'Use 5+ gallon containers. Water every 1-2 days in summer but allow slight drying between for hotter peppers.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/bell-peppers' },
        { name: 'Gardening Know How', url: 'https://www.gardeningknowhow.com/edible/vegetables/pepper/growing-habanero-peppers.htm' },
      ],
    },
  },
  {
    id: 'peas',
    name: 'Peas',
    emoji: '🟢',
    type: 'cool',
    difficulty: 'Easy',
    minTempF: 40,
    idealTempRange: [55, 75],
    indoorStartWeeks: null,
    weeksAfterLastFrost: 0,
    daysToHarvest: 60,
    vessel: 'Medium container (3+ gal) with trellis',
    companions: ['Carrots', 'Radishes', 'Lettuce'],
    avoid: ['Onion', 'Garlic'],
    plantMonths: [1, 2, 3, 9, 10],
    description: 'Direct sow in cool weather — peas fix nitrogen and improve soil. Provide a trellis or netting. Harvest frequently to keep plants producing.',
    watering: {
      seedling: { frequencyDays: 1, depthInches: 0.5, notes: 'Keep soil moist until germination. Soak pea seeds overnight before planting for faster sprouting.' },
      juvenile: { frequencyDays: 2, depthInches: 1, notes: 'Water deeply every 2 days. Consistent moisture is especially important when peas begin flowering.' },
      established: { frequencyDays: 3, depthInches: 1, notes: 'About 1 inch per week. Increase to twice-weekly watering during pod development for sweet, plump peas.' },
      method: 'Water at the base in the morning. Avoid overhead watering during flowering to prevent blossom drop.',
      mulchAdvice: 'Mulch with 2 inches of straw to keep roots cool as temperatures warm. Peas stop producing when it gets hot.',
      containerNote: 'Trellised containers dry out faster due to wind exposure. Check soil moisture every 1-2 days.',
      sources: [
        { name: 'Old Farmer\'s Almanac', url: 'https://www.almanac.com/plant/peas' },
        { name: 'Gardening Know How', url: 'https://www.gardeningknowhow.com/edible/vegetables/peas/watering-pea-plants.htm' },
      ],
    },
  },
]
