export const PLANTS = [
  {
    id: 'tomato',
    name: 'Tomato',
    emoji: '🍅',
    type: 'warm',
    difficulty: 'Moderate',
    minTempF: 50,
    idealTempRange: [65, 85],
    indoorStartWeeks: 6,
    weeksAfterLastFrost: 2,
    daysToHarvest: 70,
    vessel: 'Large container (5+ gal) or in-ground',
    companions: ['Basil', 'Kale', 'Carrots'],
    avoid: ['Fennel'],
    plantMonths: [3, 4, 5, 6],
    description: 'The summer garden staple. Needs full sun, consistent water, and support staking.',
  },
  {
    id: 'basil',
    name: 'Basil',
    emoji: '🌿',
    type: 'warm',
    difficulty: 'Easy',
    minTempF: 55,
    idealTempRange: [70, 90],
    indoorStartWeeks: 4,
    weeksAfterLastFrost: 2,
    daysToHarvest: 25,
    vessel: 'Small pot (1+ gal) or window box',
    companions: ['Tomato', 'Zucchini', 'Bell Pepper'],
    avoid: ['Sage'],
    plantMonths: [4, 5, 6, 7],
    description: 'Thrives in heat. Plant near tomatoes for pest deterrence and great flavor pairing.',
  },
  {
    id: 'zucchini',
    name: 'Zucchini',
    emoji: '🥒',
    type: 'warm',
    difficulty: 'Easy',
    minTempF: 60,
    idealTempRange: [70, 95],
    indoorStartWeeks: 3,
    weeksAfterLastFrost: 2,
    daysToHarvest: 50,
    vessel: 'Large container (10+ gal) or in-ground',
    companions: ['Basil', 'Lettuce', 'Bush Beans'],
    avoid: ['Potato'],
    plantMonths: [4, 5, 6, 7],
    description: 'Incredibly productive. Harvest frequently to encourage more fruit.',
  },
  {
    id: 'bush-beans',
    name: 'Bush Beans',
    emoji: '🫘',
    type: 'warm',
    difficulty: 'Easy',
    minTempF: 60,
    idealTempRange: [65, 85],
    indoorStartWeeks: null,
    weeksAfterLastFrost: 2,
    daysToHarvest: 55,
    vessel: 'Medium container (3+ gal) or in-ground',
    companions: ['Carrots', 'Zucchini', 'Swiss Chard'],
    avoid: ['Onion', 'Fennel'],
    plantMonths: [4, 5, 6, 7],
    description: 'Direct sow only — no transplanting needed. No staking. Perfect for beginners.',
  },
  {
    id: 'bell-pepper',
    name: 'Bell Pepper',
    emoji: '🫑',
    type: 'warm',
    difficulty: 'Moderate',
    minTempF: 55,
    idealTempRange: [70, 90],
    indoorStartWeeks: 8,
    weeksAfterLastFrost: 2,
    daysToHarvest: 75,
    vessel: 'Medium container (3+ gal) or in-ground',
    companions: ['Basil', 'Tomato', 'Carrots'],
    avoid: ['Fennel'],
    plantMonths: [4, 5, 6],
    description: 'Start early indoors — peppers love a long warm season. Keep soil consistently moist.',
  },
  {
    id: 'lettuce',
    name: 'Lettuce',
    emoji: '🥬',
    type: 'cool',
    difficulty: 'Easy',
    minTempF: 40,
    idealTempRange: [45, 75],
    indoorStartWeeks: 4,
    weeksAfterLastFrost: 0,
    daysToHarvest: 30,
    vessel: 'Shallow container (6+ in deep) or window box',
    companions: ['Carrots', 'Tomato', 'Sugar Snaps'],
    avoid: ['Celery'],
    plantMonths: [1, 2, 3, 9, 10, 11],
    description: 'Cool-season superstar. In Zone 9b, plant spring and fall. Bolts in summer heat.',
  },
  {
    id: 'kale',
    name: 'Kale',
    emoji: '🥦',
    type: 'cool',
    difficulty: 'Easy',
    minTempF: 35,
    idealTempRange: [45, 75],
    indoorStartWeeks: 4,
    weeksAfterLastFrost: 0,
    daysToHarvest: 60,
    vessel: 'Medium container (3+ gal) or in-ground',
    companions: ['Bush Beans', 'Carrots', 'Sugar Snaps'],
    avoid: ['Tomato', 'Strawberry'],
    plantMonths: [1, 2, 3, 9, 10, 11],
    description: 'Hardy and frost-tolerant. In Zone 9b, kale can grow nearly year-round.',
  },
  {
    id: 'carrots',
    name: 'Carrots',
    emoji: '🥕',
    type: 'cool',
    difficulty: 'Moderate',
    minTempF: 40,
    idealTempRange: [60, 75],
    indoorStartWeeks: null,
    weeksAfterLastFrost: 0,
    daysToHarvest: 75,
    vessel: 'Deep container (12+ in) or in-ground',
    companions: ['Lettuce', 'Kale', 'Tomato'],
    avoid: ['Dill', 'Fennel'],
    plantMonths: [1, 2, 3, 9, 10],
    description: 'Direct sow only — carrots hate being transplanted. Needs deep, loose, rock-free soil.',
  },
  {
    id: 'sugar-snaps',
    name: 'Sugar Snaps',
    emoji: '🫛',
    type: 'cool',
    difficulty: 'Easy',
    minTempF: 40,
    idealTempRange: [55, 75],
    indoorStartWeeks: null,
    weeksAfterLastFrost: 0,
    daysToHarvest: 60,
    vessel: 'Medium container (3+ gal) with trellis or cage',
    companions: ['Lettuce', 'Carrots', 'Swiss Chard'],
    avoid: ['Onion', 'Garlic'],
    plantMonths: [1, 2, 3, 9, 10],
    description: 'Sweet, crisp, and easy. Direct sow in cool weather. Needs a trellis to climb.',
  },
  {
    id: 'swiss-chard',
    name: 'Swiss Chard',
    emoji: '🌱',
    type: 'cool',
    difficulty: 'Easy',
    minTempF: 40,
    idealTempRange: [50, 80],
    indoorStartWeeks: 4,
    weeksAfterLastFrost: 0,
    daysToHarvest: 55,
    vessel: 'Medium container (3+ gal) or in-ground',
    companions: ['Bush Beans', 'Carrots', 'Sugar Snaps'],
    avoid: ['Corn'],
    plantMonths: [1, 2, 3, 8, 9, 10, 11],
    description: 'Colorful and versatile. More heat-tolerant than lettuce. Harvest outer leaves continuously.',
  },
  {
    id: 'thyme',
    name: 'Thyme',
    emoji: '🌿',
    type: 'warm',
    difficulty: 'Easy',
    minTempF: 30,
    idealTempRange: [60, 80],
    indoorStartWeeks: 8,
    weeksAfterLastFrost: 0,
    daysToHarvest: 90,
    vessel: 'Small pot (1+ gal) or herb garden',
    companions: ['Tomato', 'Eggplant', 'Lavender'],
    avoid: ['Basil'],
    plantMonths: [3, 4, 5, 9, 10],
    description: 'Drought-tolerant perennial herb. Thrives in well-drained soil and full sun. Trim regularly to keep bushy.',
  },
  {
    id: 'parsley',
    name: 'Parsley',
    emoji: '🌿',
    type: 'cool',
    difficulty: 'Easy',
    minTempF: 40,
    idealTempRange: [50, 75],
    indoorStartWeeks: 6,
    weeksAfterLastFrost: 0,
    daysToHarvest: 70,
    vessel: 'Small pot (1+ gal) or window box',
    companions: ['Tomato', 'Carrots', 'Lettuce'],
    avoid: ['Mint'],
    plantMonths: [2, 3, 4, 9, 10, 11],
    description: 'Slow to germinate (2–4 weeks) — be patient. Biennial that grows well in Zone 9b fall through spring.',
  },
  {
    id: 'radishes',
    name: 'Radishes',
    emoji: '🔴',
    type: 'cool',
    difficulty: 'Easy',
    minTempF: 40,
    idealTempRange: [50, 65],
    indoorStartWeeks: null,
    weeksAfterLastFrost: 0,
    daysToHarvest: 25,
    vessel: 'Shallow container (6+ in deep) or in-ground',
    companions: ['Carrots', 'Lettuce', 'Peas'],
    avoid: ['Hyssop'],
    plantMonths: [1, 2, 3, 9, 10, 11],
    description: 'One of the fastest crops from seed to harvest. Direct sow every 2 weeks for continuous supply. Bolts quickly in heat.',
  },
  {
    id: 'onions',
    name: 'Long Day Onions',
    emoji: '🧅',
    type: 'cool',
    difficulty: 'Moderate',
    minTempF: 35,
    idealTempRange: [55, 75],
    indoorStartWeeks: 8,
    weeksAfterLastFrost: 0,
    daysToHarvest: 100,
    vessel: 'Medium container (3+ gal, 6+ in deep) or in-ground',
    companions: ['Carrots', 'Lettuce', 'Tomato'],
    avoid: ['Peas', 'Bush Beans'],
    plantMonths: [1, 2, 3],
    description: 'Long day varieties need 14–16 hrs of daylight to bulb. Start from seed indoors in winter for spring transplant. Cure after harvest.',
  },
  {
    id: 'poblano-pepper',
    name: 'Poblano Pepper',
    emoji: '🌶️',
    type: 'warm',
    difficulty: 'Moderate',
    minTempF: 55,
    idealTempRange: [70, 85],
    indoorStartWeeks: 8,
    weeksAfterLastFrost: 2,
    daysToHarvest: 75,
    vessel: 'Medium container (5+ gal) or in-ground',
    companions: ['Basil', 'Tomato', 'Carrots'],
    avoid: ['Fennel'],
    plantMonths: [4, 5, 6],
    description: 'Mild, rich-flavored pepper — perfect for stuffing. Dries into ancho chilis. Needs warm soil and consistent water.',
  },
  {
    id: 'shishito-pepper',
    name: 'Shishito Pepper',
    emoji: '🌶️',
    type: 'warm',
    difficulty: 'Easy',
    minTempF: 55,
    idealTempRange: [70, 85],
    indoorStartWeeks: 8,
    weeksAfterLastFrost: 2,
    daysToHarvest: 60,
    vessel: 'Medium container (3+ gal) or in-ground',
    companions: ['Basil', 'Tomato', 'Marigolds'],
    avoid: ['Fennel'],
    plantMonths: [4, 5, 6],
    description: 'Prolific producer of thin-walled, mild peppers. Pick when green and blister in a hot pan. 1 in 10 is spicy!',
  },
  {
    id: 'thai-chili',
    name: 'Thai Chili',
    emoji: '🌶️',
    type: 'warm',
    difficulty: 'Moderate',
    minTempF: 60,
    idealTempRange: [75, 90],
    indoorStartWeeks: 10,
    weeksAfterLastFrost: 3,
    daysToHarvest: 80,
    vessel: 'Medium container (3+ gal) or in-ground',
    companions: ['Basil', 'Tomato', 'Marigolds'],
    avoid: ['Fennel'],
    plantMonths: [4, 5, 6],
    description: 'Compact plants loaded with small, fiery peppers (50,000–100,000 SHU). Ornamental and edible. Loves Zone 9b summers.',
  },
  {
    id: 'eggplant',
    name: 'Long Purple Eggplant',
    emoji: '🍆',
    type: 'warm',
    difficulty: 'Moderate',
    minTempF: 60,
    idealTempRange: [70, 85],
    indoorStartWeeks: 8,
    weeksAfterLastFrost: 3,
    daysToHarvest: 70,
    vessel: 'Large container (5+ gal) or in-ground',
    companions: ['Basil', 'Thyme', 'Marigolds'],
    avoid: ['Fennel', 'Tomato'],
    plantMonths: [4, 5, 6],
    description: 'Slender, tender Italian-style eggplant. Harvest when skin is glossy — dull skin means overripe. Loves heat and full sun.',
  },
  {
    id: 'summer-squash',
    name: 'Summer Squash',
    emoji: '🟡',
    type: 'warm',
    difficulty: 'Easy',
    minTempF: 60,
    idealTempRange: [70, 95],
    indoorStartWeeks: 3,
    weeksAfterLastFrost: 2,
    daysToHarvest: 50,
    vessel: 'Large container (10+ gal) or in-ground',
    companions: ['Basil', 'Marigolds', 'Bush Beans'],
    avoid: ['Potato'],
    plantMonths: [4, 5, 6, 7],
    description: 'Fast-growing and very productive. Harvest young (6–8 in) for best flavor. Check plants daily — they grow quickly!',
  },
  {
    id: 'cucumber',
    name: 'Cucumber (Poinsett 76)',
    emoji: '🥒',
    type: 'warm',
    difficulty: 'Easy',
    minTempF: 60,
    idealTempRange: [65, 85],
    indoorStartWeeks: 3,
    weeksAfterLastFrost: 2,
    daysToHarvest: 65,
    vessel: 'Large container (5+ gal) with trellis or in-ground',
    companions: ['Lettuce', 'Peas', 'Radishes'],
    avoid: ['Potato', 'Melon'],
    plantMonths: [4, 5, 6, 7],
    description: 'Disease-resistant slicing cucumber. Poinsett 76 tolerates heat and humidity well. Trellis for straight fruit and better airflow.',
  },
  {
    id: 'zinnias',
    name: 'Zinnias',
    emoji: '🌸',
    type: 'warm',
    difficulty: 'Easy',
    minTempF: 55,
    idealTempRange: [70, 90],
    indoorStartWeeks: 4,
    weeksAfterLastFrost: 2,
    daysToHarvest: 60,
    vessel: 'Medium container (3+ gal) or garden bed',
    companions: ['Tomato', 'Marigolds', 'Basil'],
    avoid: [],
    plantMonths: [4, 5, 6, 7],
    description: 'Salmon Queen and multicolor mix. Cut-and-come-again flowers — the more you cut, the more they bloom. Pollinators love them.',
  },
  {
    id: 'violas',
    name: 'Petite Violas (Fairyland)',
    emoji: '💜',
    type: 'cool',
    difficulty: 'Easy',
    minTempF: 25,
    idealTempRange: [40, 70],
    indoorStartWeeks: 8,
    weeksAfterLastFrost: 0,
    daysToHarvest: 60,
    vessel: 'Small pot (1+ gal) or window box',
    companions: ['Lettuce', 'Kale', 'Parsley'],
    avoid: [],
    plantMonths: [9, 10, 11, 1, 2],
    description: 'Dainty edible flowers — gorgeous in salads and on cakes. Extremely cold-hardy. Bloom through Zone 9b winter.',
  },
  {
    id: 'french-alouette',
    name: 'Ranunculus (French Alouette)',
    emoji: '🌹',
    type: 'cool',
    difficulty: 'Moderate',
    minTempF: 25,
    idealTempRange: [45, 65],
    indoorStartWeeks: null,
    weeksAfterLastFrost: 0,
    daysToHarvest: 90,
    vessel: 'Medium container (3+ gal) or garden bed',
    companions: ['Violas', 'Lavender', 'Lettuce'],
    avoid: [],
    plantMonths: [10, 11, 12, 1],
    description: 'Plant pre-soaked corms in fall for stunning spring blooms. French Alouette series produces densely-petalled, rose-like flowers. Excellent cut flower.',
  },
  {
    id: 'lavender',
    name: 'Fernleaf Lavender',
    emoji: '💐',
    type: 'warm',
    difficulty: 'Easy',
    minTempF: 40,
    idealTempRange: [60, 80],
    indoorStartWeeks: 10,
    weeksAfterLastFrost: 2,
    daysToHarvest: 90,
    vessel: 'Medium container (3+ gal) with excellent drainage',
    companions: ['Thyme', 'Rosemary', 'Marigolds'],
    avoid: ['Mint'],
    plantMonths: [3, 4, 5],
    description: 'Fernleaf (Lavandula multifida) has lacy, fern-like foliage and blooms nearly year-round in Zone 9b. Drought-tolerant once established.',
  },
  {
    id: 'marigolds',
    name: 'Marigolds',
    emoji: '🏵️',
    type: 'warm',
    difficulty: 'Easy',
    minTempF: 55,
    idealTempRange: [65, 85],
    indoorStartWeeks: 4,
    weeksAfterLastFrost: 2,
    daysToHarvest: 50,
    vessel: 'Small pot (1+ gal) or garden border',
    companions: ['Tomato', 'Basil', 'Peppers'],
    avoid: [],
    plantMonths: [4, 5, 6, 7],
    description: 'The ultimate companion plant — repels aphids, whiteflies, and nematodes. Deadhead spent blooms for continuous flowering.',
  },
  {
    id: 'calabrian-chili',
    name: 'Calabrian Chili',
    emoji: '🌶️',
    type: 'warm',
    difficulty: 'Moderate',
    minTempF: 60,
    idealTempRange: [75, 90],
    indoorStartWeeks: 10,
    weeksAfterLastFrost: 3,
    daysToHarvest: 80,
    vessel: 'Medium container (3+ gal) or in-ground',
    companions: ['Basil', 'Tomato', 'Marigolds'],
    avoid: ['Fennel'],
    plantMonths: [4, 5, 6],
    description: 'Italian heirloom pepper with fruity, medium heat (25,000–40,000 SHU). Famous in Calabrian chili paste. Ripens from green to deep red.',
  },
  {
    id: 'bok-choy',
    name: 'Bok Choy',
    emoji: '🥬',
    type: 'cool',
    difficulty: 'Easy',
    minTempF: 35,
    idealTempRange: [45, 75],
    indoorStartWeeks: 4,
    weeksAfterLastFrost: 0,
    daysToHarvest: 45,
    vessel: 'Shallow container (6+ in deep) or in-ground',
    companions: ['Carrots', 'Lettuce', 'Onions'],
    avoid: ['Strawberry'],
    plantMonths: [2, 3, 4, 9, 10, 11],
    description: 'Fast-growing Asian green — harvest baby bok choy at 6 in or let it mature. Bolts quickly in heat, so plant in cool months.',
  },
  {
    id: 'habanero',
    name: 'Habanero',
    emoji: '🔥',
    type: 'warm',
    difficulty: 'Moderate',
    minTempF: 60,
    idealTempRange: [75, 90],
    indoorStartWeeks: 10,
    weeksAfterLastFrost: 3,
    daysToHarvest: 100,
    vessel: 'Medium container (5+ gal) or in-ground',
    companions: ['Basil', 'Tomato', 'Marigolds'],
    avoid: ['Fennel'],
    plantMonths: [4, 5, 6],
    description: 'Very hot (100,000–350,000 SHU) with fruity, tropical flavor. Start very early indoors — needs a long, warm season. Prolific once producing.',
  },
  {
    id: 'peas',
    name: 'Peas',
    emoji: '🟢',
    type: 'cool',
    difficulty: 'Easy',
    minTempF: 40,
    idealTempRange: [55, 75],
    indoorStartWeeks: null,
    weeksAfterLastFrost: 0,
    daysToHarvest: 60,
    vessel: 'Medium container (3+ gal) with trellis',
    companions: ['Carrots', 'Radishes', 'Lettuce'],
    avoid: ['Onion', 'Garlic'],
    plantMonths: [1, 2, 3, 9, 10],
    description: 'Direct sow in cool weather — peas fix nitrogen and improve soil. Provide a trellis or netting. Harvest frequently to keep plants producing.',
  },
]
